import { Button, VerticalBox, AboutSlint, Slider, StandardButton, CheckBox , HorizontalBox} from "std-widgets.slint";

// import "./zpix.ttf";
import "./LXGWWenKai-Regular.ttf";

export component AppWindow inherits Window {
    default-font-family: "LXGW WenKai";
    default-font-size: 20px;
    default-font-weight: 800;

    width: 536px;
    height: 240px;
    in-out property<int> counter: 42;
    callback request-increase-value();
    background: @linear-gradient(90deg, #3f87a6 0%, #ebf8e1 50%, #f69d3c 100%);

    VerticalBox {
        Text {
            text: "Counter: \{root.counter} Value: \{round(slider.value)}";
            color: #08404f;
            font-size: 20px;
        }
        Rectangle {
            background: #002b36;
            Button {
                text: "增加 ++";
                clicked => {
                    root.request-increase-value();
                    debug("clicked");
                }
            }
        }
        slider := Slider {
            maximum: 100;
        }
    //  CheckBox {
    //     text: "Check me";
    // }
        HorizontalBox {
            Button {
                text: "Reset";
                clicked => {
                    slider.value = 0;
                    root.counter = 0;
                }
            }
            Button { text: "About"; }
        }
        Text {
            text: "中文测试 © @bh1xuw";
            color: #eee;
            font-size: 16px;
        }
    }

}

